export type DiagramNode = {id: string; number: string; time: string | null; group: string; subject: string; subject_ref: string; event: string; category: string; source_ids: string[]; message_id: string; notes: string[]}
export type DiagramPage = {number: number; mermaid: string; nodes: DiagramNode[]; groups: {title: string; node_ids: string[]}[]; edges: {from: string; to: string; kind: string}[]}
export type EventDiagram = {version: "1.0"; status: "ready" | "partial" | "empty" | "unavailable"; run_id: string | null; scenario_id: string; timezone: string; window_start: string; window_end: string; scenario_snapshot_id: string; records_snapshot_id: string; rule_version: string; synthetic: boolean; total_nodes: number; pages: DiagramPage[]; legend: string; aliases: {name: string; ref: string}[]; missing: string[]; case_window?: string[]; case_source_ids?: string[]}
function record(value: unknown): value is Record<string, unknown> {return !!value && typeof value === "object" && !Array.isArray(value)}
function texts(value: unknown): value is string[] {return Array.isArray(value) && value.every(x => typeof x === "string")}
export function isDiagram(value: unknown): value is EventDiagram {
 if (!record(value) || value.version !== "1.0" || !["ready","partial","empty","unavailable"].includes(String(value.status)) || !texts(value.missing) || !Array.isArray(value.pages) || value.pages.length > 100) return false
 if (!["scenario_id","timezone","window_start","window_end","scenario_snapshot_id","records_snapshot_id","rule_version","legend"].every(k => typeof value[k] === "string") || !Array.isArray(value.aliases) || !value.aliases.every(x=>record(x)&&typeof x.name === "string"&&typeof x.ref === "string")) return false
 return value.pages.every(p => record(p) && typeof p.number === "number" && typeof p.mermaid === "string" && p.mermaid.length <= 65536 && p.mermaid.startsWith("flowchart TB\n") && !/(%%|<|\bclick\b|\bhref\b|\bclassDef\b|\bstyle\b)/i.test(p.mermaid) && Array.isArray(p.nodes) && p.nodes.length <= 20 && p.nodes.every(n => record(n) && ["id","number","subject","subject_ref","event","category","group","message_id"].every(k=>typeof n[k] === "string") && (n.time === null || typeof n.time === "string") && texts(n.source_ids) && texts(n.notes)))
}
export function exportName(diagram: EventDiagram, page: number, format: "svg" | "png") {return `事件脉络图-${diagram.scenario_id.replace(/[^a-zA-Z0-9_-]/g, "_")}-第${page}页.${format}`}
