import { test, expect } from 'bun:test';
import { readFile } from 'node:fs/promises';
import { compile, checkClaims } from './facts-plugin/engine.mjs';
import plugin from './facts-plugin/entry.mjs';
const data=JSON.parse(await readFile(new URL('./facts-plugin/fixtures.json',import.meta.url),'utf8'));
const theft=data.scenarios['DEMO-CASE-THEFT'];
const gambling=data.scenarios['DEMO-CASE-GAMBLING'];
test('explicit field mapping excludes other subjects; frame and trip retain meanings',()=>{
 const t=compile(theft,data.records);const ids=t.facts.map(f=>f.fact_id);
 expect(ids).toContain('DEMO-NGT-001');expect(ids).toContain('DEMO-NGT-007');expect(ids).not.toContain('DEMO-NGT-004');
 expect(t.summary.find(x=>x.module==='night').count).toBe(2);
 expect(t.facts.find(x=>x.fact_id==='DEMO-POR-002').statement).toContain('同框（不据此推导同行）');
 expect(t.facts.find(x=>x.fact_id==='DEMO-POR-006').statement).toContain('明确同行');
 expect(t.summary.find(x=>x.module==='vehicle').count).toBe(2);
});
test('alone needs independent observation, never absence or another scenario',()=>{
 const t=compile(theft,data.records),g=compile(gambling,data.records);
 expect(t.facts.find(f=>f.fact_id==='DEMO-NGT-001').statement).toContain('无法判断');
 expect(t.facts.find(f=>f.fact_id==='DEMO-NGT-007').source_ids).toContain('DEMO-DOC-T02');
 expect(t.facts.find(f=>f.fact_id==='DEMO-NGT-007').statement).toContain('明确独行');
 expect(g.facts.find(f=>f.fact_id==='DEMO-NGT-007').statement).toContain('无法判断');
});
test('night timezone, half-open observation window and unpaired funds',()=>{
 const records=structuredClone(data.records);
 records.night.records=['2026-09-14T13:59:00Z','2026-09-14T14:00:00Z','2026-09-14T21:59:00Z','2026-09-14T22:00:00Z','2026-09-15T16:00:00Z'].map((time,i)=>({...records.night.records[0],record_id:'TEST-'+i,occurred_at:time}));
 const t=compile(gambling,records);expect(t.summary.find(x=>x.module==='night')).toMatchObject({count:4,night_count:2});
 expect(t.summary.find(x=>x.module==='funds').count).toBe(3);
 records.funds.records.push(records.funds.records[0]);expect(()=>compile(gambling,records)).toThrow('duplicate_record_id');
});
test('real ID cannot justify altered claim; snapshots cannot be swapped',()=>{
 const t=compile(theft,data.records),f=t.facts.find(f=>f.fact_id==='DEMO-NGT-001');
 const good={fact_id:f.fact_id,statement:f.statement,source_ids:f.source_ids};
 const checked=checkClaims(t,[good,{...good,statement:'明确独行并实施盗窃'}]);
 expect(checked.approved.length).toBe(1);expect(checked.rejected.length).toBe(1);
 expect(checked.scenario_snapshot_id).not.toBe(checked.records_snapshot_id);
 expect(checkClaims(t,[{...good,source_ids:['DEMO-NGT-007']}]).approved).toEqual([]);
});
test('fixed service calls return only scoped facts; version mismatch becomes partial and unknown',async()=>{
 const calls=[];const p=await plugin({}, {}, {connections:{request:async(alias,request)=>{calls.push(request.json.module);return {status:200,data:data.records[request.json.module]}}}});
 const result=JSON.parse(await p.tool.peixian_prepare_scenario_facts.execute({scenario_id:theft.scenario_id}));
 expect(calls).toEqual(['night','portrait','vehicle']);expect(result.data_status).toBe('complete');expect(result).not.toHaveProperty('records');
 const fail=await plugin({}, {}, {connections:{request:async()=>({status:503,data:{}})}});
 const partial=JSON.parse(await fail.tool.peixian_prepare_scenario_facts.execute({scenario_id:theft.scenario_id}));
 expect(partial.data_status).toBe('partial');expect(partial.summary).toEqual([]);expect(partial.facts.some(x=>x.fact_id==='DEMO-CTX-T02')).toBe(false);
});

test('all backend trusted projections are generated by the same executable compiler',async()=>{
 const generated=JSON.parse(await readFile(new URL('../../../../services/peixian-control/control/scenario_fact_tables.json',import.meta.url),'utf8'));
 const computed=[];
 for(const scenario of Object.values(data.scenarios))for(let mask=0;mask<(1<<scenario.required_modules.length);mask++)computed.push(compile(scenario,Object.fromEntries(scenario.required_modules.filter((_,i)=>mask&(1<<i)).map(m=>[m,data.records[m]]))));
 expect(generated).toEqual(computed);
});
